ЛР/ЛР1/ЕД-23-1 підгрупа 2/LW1.sql

LW1.Chornoi

---

ЛР/ЛР2/LW2.Chornoi.sql

LW2.Chornoi

---

ЛР/ЛР1/ЕД-23-1 підгрупа 1/LW1Sidorenko.sql

LW1Sidorenko

---

ЛР/ЛР2/ЕД-23-1 підгрупа 2/LW2.NEBABA.sql

LW2.NEBABA

---

ЛР/ЛР3/ЕД-23-1 підгрупа 1/LW3GrisheninaSofia.sql

LW3GrisheninaSofia

---

ЛР/ЛР1/ЕД-23-1 підгрупа 1/LW1katsapova.sql

LW1katsapova

---

ЛР/ЛР2/ЕД-23-1 підгрупа 1/SQLQuery3.sql

LW2katsapova

---

ЛЕКЦІЇ/T2.DataTupes-DDL-Constraints.sql

T2-DataTupes-DDL-Constraints

---

ЛР/ЛР3/LW3.NEBABA.sql

LW3.NEBABA

---

ЛР/ЛР3/ЕД-23-2 підгрупа 2 ЕД-23-3 підгрупа 1/LW3Vovchok.sql

LW3Vovchok

---

ЛР/ЛР5/LW5Grishenina.sql

LW5Grishenina

---

LW5DANYLCHENKO.sql

LW5DANYLCHENKO

---

ЛР/ЛР3/ЕД-23-1 підгрупа 1/LW3Korchahina.sql

LW3Korchahina

---

ЛЕКЦІЇ/T3.Select.Predicates.StringFunctions.sql

T3.Select.Predicates.StringFunctions

T3.Select.Predicates.StringFunctions

---

ЛР/ЛР3/LW3.Mieshkova.sql

LW3.Mieshkova

---

ЛР/ЛР2/ЕД-23-1 підгрупа 2/LW2.Kravchuk.sql

LW2.Kravchuk

---

ЛР/ЛР3/LW3.Kravchuk.sql

LW3.Kravchuk

---

ЛР/ЛР5/LW5.NEBABA.sql

LW5.NEBABA

---

ЛР/ЛР3/ЕД-23-2 підгрупа 2 ЕД-23-3 підгрупа 1/LW3.ZHURAVEL.sql

LW3.ZHURAVEL

---

ЛР/ЛР5/ЕД-23-1 підгрупа 1/LW5katsapova.sql

LW5katsapova

---

ЛР/ЛР6/ЕД-23-2 підгрупа 2  ЕД-23-3 підгрупа 1/LW6Vovchok.sql

LW6Vovchok

---

ЛЕКЦІЇ/T5.Subqueries.sql

T5.Subqueries

---

ЛР/ЛР5/ЕД-23-1 підгрупа 2/LW5.Mieshkova.sql

LW5.Mieshkova

---

ЛР/ЛР2/ЕД-23-1 підгрупа 2/LW2.Naumenko.sql

LW2.Naumenko

---

ЛР/ЛР3/ЕД-23-1 підгрупа 1/Підгруппа 2/LW3.NAUMENKO.sql

LW3.NAUMENKO

---

ЛР/ЛР5/ЕД-23-1 підгрупа 2/LW5.NAUMENKO.sql

LW5.NAUMENKO

---

ЛР/ЛР3/ЕД-23-2 підгрупа 2 ЕД-23-3 підгрупа 1/LW3.sql

LW3Snihurska

---

ЛР/ЛР5/ЕД-23-2 підгрупа 2 ЕД-23-3 підгрупа 1/LW5-1.sql
ЛР/ЛР5/ЕД-23-2 підгрупа 2 ЕД-23-3 підгрупа 1/LW5.sql

LW5Snihurska

---

ЛР/ЛР3/ЕД-23-2/LW3KOMOHORTSEVA.sql

LW3KOMOHORTSEVA

---

ЛР/ЛР5/ЕД-23-2 підгрупа 2 ЕД-23-3 підгрупа 1/LW5KOMOHORTSEVA.sql

LW5KOMOHORTSEVA

---

ЛР/ЛР2/ЕД-23-2 підгрупа 2 ЕД-23-3 підгрупа 1/LW2TSIPINSKY.sql

LW2Tsipinsky

---

ЛР/ЛР3/ЕД-23-2 підгрупа 2 ЕД-23-3 підгрупа 1/LW3TSIPINSKY.sql

LW3Tsipindky

---

ЛР/ЛР5/ЕД-23-2 підгрупа 2 ЕД-23-3 підгрупа 1/LW5-1TSIPINSKY.sql
ЛР/ЛР5/ЕД-23-2 підгрупа 2 ЕД-23-3 підгрупа 1/LW5-2TSIPINSKY.sql

LW5sipinsky

---

ЛР/ЛР7/ЕД-23-2 підгрупа 2 ЕД-23-3 підгрупа 1/LW7Vovchok.sql

LW7Vovchok

---

ЛР/ЛР2/ЕД-23-2 підгрупа 2 ЕД-23-3 підгрупа 1/SQLQuery1.sql

lw2vaselets

---

ЛР/ЛР1/ЕД-23-2 підгрупа 2  ЕД-23-3 підгрупа 1/LW1TSIPINSKY.sql

LW1Tsipinsky

---

ЛР/ЛР3/LW3.NEBABA.2.sql

LW3.NEBABA.2

---

ЛР/ЛР2/ЕД-23-1 підгрупа 2/LW2.Mieshkova.sql

LW2.Mieshkova

---

ЛР/ЛР1/ЕД-23-1 підгрупа 2/LW1Mieshkova.sql

LW1Mieshkova
